"""empty message

Revision ID: b53e1e5f3587
Revises: 6937044217dc
Create Date: 2022-08-10 09:19:07.729423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53e1e5f3587'
down_revision = '6937044217dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=2200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website')
    op.drop_column('users', 'name')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
