"""empty message

Revision ID: 6937044217dc
Revises: ed0d5d2a388a
Create Date: 2022-07-16 10:39:01.529864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6937044217dc'
down_revision = 'ed0d5d2a388a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'photo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('image', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    op.alter_column('comments', 'photo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
